name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Unit test
      run: ./gradlew testDebugUnitTest --continue
    - name: Collect test results
      run: |
            mkdir -p ~/unit/
            find . -type f -regex ".*/build/test-results/.*xml" \
                -exec cp {} ~/junit/ \;
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Test results
        path: ~/unit
